---
- name: Convert openssl certificate to jks format
  shell: openssl jks
- name: Create a ConfigMap that has the file hazelcast-client.xml
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: hazelcast-client
        namespace: default
      data:
        hazelcast-client.xml: |
          <hazelcast-client xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                  http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.3.xsd">
              <cluster-name>hz-primary</cluster-name>
              <instance-name>tx-prod</instance-name>
              <client-labels>
                  <label>tx-prod</label>
              </client-labels>
              <network>
                  <cluster-members>
                      <address>hz-primary.default.svc.cluster.local:5701</address>
                  </cluster-members>
                  <smart-routing>true</smart-routing>
                  <ssl enabled="false">
                      <factory-class-name>com.hazelcast.nio.ssl.BasicSSLContextFactory</factory-class-name>
                      <properties>
                          <property name="trustStore">/etc/hazelcast/ssl/hazelcast.jks</property>
                          <property name="trustStorePassword">hazelcast</property>
                      </properties>
                  </ssl>
              </network>
          </hazelcast-client>
  tags:
    - tx-prod
    - busybox
- name: Create a busy box container configuring the config map as a volume
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: busybox
        namespace: default
      spec:
        containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'while true; do sleep 3600; done']
          volumeMounts:
          - name: hazelcast-client
            mountPath: /etc/hazelcast
          - name: hazelcast-client-truststore
            mountPath: /etc/hazelcast/ssl
            readOnly: true
        volumes:
        - name: hazelcast-client
          configMap:
            name: hazelcast-client
        - name: hazelcast-client-truststore
          configMap:
            name: hazelcast-keystore
  tags:
    - tx-prod
    - busybox
- name: Register all the IPs of the hz-primary cluster
  shell: kubectl get service -l=app.kubernetes.io/instance=hz-primary,hazelcast.com/service-per-pod -o=jsonpath="{range .items[*]}{.status.loadBalancer.ingress[0].ip}{','}{end}" | sed 's/.$//'
  register: hz_primary_ips
  tags:
    - tx-prod
- name: Hazelcast primary IPs
  debug:
    msg: "Hz Primary cluster IPs : {{ hz_primary_ips.stdout }}"
  tags:
    - tx-prod
- name: Run the TransactionProducer class
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Job
      metadata:
        name: tx-prod
        namespace: default
      spec:
        template:
          spec:
            containers:
              - name: tx-prod
                image: "{{ region }}-docker.pkg.dev/{{ project_id }}/{{ repository_id }}/java-app"
                imagePullPolicy: Always
                command: ["java", "-Dhazelcast.client.config=/etc/hazelcast/hazelcast-client.xml", "-cp", "target/tx-stream-1.0-SNAPSHOT.jar:target/lib/*", "com.hz.txstream.util.TransactionProducer"]
                env:
                  - name: JdbcHost
                    value: postgres-postgresql.default.svc.cluster.local
                  - name: JdbcPassword
                    value: hk#uT7@9
                  - name: ClusterName
                    value: hz-primary
                  - name: ServerIP
                    value: "{{ hz_primary_ips.stdout }}"
                  - name: TransactionProducerDelay
                    value: "0"
                  - name: TransactionToProduce
                    value: "100000"
                volumeMounts:
                  - name: hazelcast-client
                    mountPath: /etc/hazelcast
                  - name: hazelcast-client-truststore
                    mountPath: /etc/hazelcast/ssl
                    readOnly: true
            volumes:
              - name: hazelcast-client
                configMap:
                  name: hazelcast-client
              #create volume from secret
              - name: hazelcast-client-truststore
                configMap:
                  name: hazelcast-keystore
            restartPolicy: Never
  tags:
    - tx-prod
