- name: Deploy Hazelcast cluster and application
  hosts: localhost
  tasks:
######################
## Kafka
######################
  - name: Delete Kafka Topic
    kubernetes.core.k8s:
      state: absent
      definition:
        apiVersion: kafka.strimzi.io/v1beta1
        kind: KafkaTopic
        metadata:
          name: payments
          namespace: kafka
          labels:
            strimzi.io/cluster: my-cluster
    tags:
      - kafka
      - topic
  - name: Delete Kafka Cluster
    kubernetes.core.k8s:
      state: absent
      definition:
        apiVersion: kafka.strimzi.io/v1beta2
        kind: Kafka
        metadata:
          name: my-cluster
          namespace: kafka
    tags:
      - kafka
      - cluster