- name: Deploy Hazelcast cluster and application
  hosts: localhost
# - name: Delete Hazelcast WAN replication
#   shell: "kubectl delete wanreplications.hazelcast.com hazelcast-wan-replication"

######################
## All
######################
- name: Delete everything via kubectl

  shell: "kubectl delete all --all -n {{ item }}"
  loop:
    - default
    - kafka
    - monitoring
  tags:
    - kafka
    - all