---
# tasks file for k8s/roles/postgres
- name: Add Bitnami chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"
  tags:
    - init
- name: Create PV for Postgres
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        namespace: default
        name: postgres-pv
        labels:
          type: local
      spec:
        storageClassName: manual
        capacity:
          storage: 2Gi
        accessModes:
          - ReadWriteOnce
        hostPath:
          path: "/opt/data"
  tags:
    - postgres

- name: Create PVC for Postgres
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: default
        name: postgres-pvc
      spec:
        storageClassName: manual
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  tags:
    - postgres


- name: Install Postgres using helm. Wait to be ready
  kubernetes.core.helm:
    name: postgres
    chart_ref: bitnami/postgresql
    release_namespace: default
    wait: yes
    values:
#      primary:
#        service:
#          type: LoadBalancer
      auth:
        postgresPassword: hk#uT7@9
        database: postgres
        username: postgres
#      postgresqlUsername: postgres
#      postgresqlDatabase: postgres
      persistence:
        enabled: true
        existingClaim: postgres-pvc
    state: present
  tags:
    - postgres