---
# tasks file for k8s/roles/populate-data
- name: Build an image for linux/amd64 platform
  # https://stackoverflow.com/questions/73285601/docker-exec-usr-bin-sh-exec-format-error
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html#notes
  shell: docker buildx build --platform linux/amd64 -t java-app ../
  args:
    chdir: "{{ playbook_dir }}"
    creates: java-app
  tags:
    - populate-data
    - build-image
- name: Push image to GKE Artifact Registry
  community.docker.docker_image:
    name: "java-app"
    source: local
    # https://cloud.google.com/artifact-registry/docs/docker/store-docker-container-images#add-image
    repository: "{{ region }}-docker.pkg.dev/{{ project_id }}/{{ repository_id }}/java-app:latest"
    push: yes
  tags:
    - populate-data
    - build-image

- name: Deploy the java-app image in a k8s container along with a startup container executing java class com.hz.txstream.util.GenerateAll
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Job
      metadata:
          name: load-data
          namespace: default
      spec:
        template:
          spec:
            containers:
            - name: load-data
              image: "{{ region }}-docker.pkg.dev/{{ project_id }}/{{ repository_id }}/java-app"
              imagePullPolicy: Always
              command: ["java", "-cp", "target/tx-stream-1.0-SNAPSHOT.jar:target/lib/*", "com.hz.txstream.util.GenerateAll"]
              env:
                  - name: JdbcHost
                    value: postgres-postgresql.default.svc.cluster.local
                  - name: JdbcPassword
                    value: hk#uT7@9
            restartPolicy: Never
  tags:
      - populate-data